#!/usr/bin/env bash
# Script that configures a second web server
apt update && apt install -y nginx

mkdir -p /etc/nginx
printf  "events {
	# configuration of connection processing
}

http {
	include mime.types;

	server {
		listen 80 default_server;
		listen [::]:80 default_server;
		location / {
			return 200 'Hello World!';
		}
	}

}
" > /etc/nginx/nginx.config

service nginx restart
