#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive from it
mysqldump -u root -p"$1" --all-databases > backup.sql
sudo tar -zcvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
