#!/usr/bin/env bash
# Script that automates fix for Ubuntu container Nginx installation
sed -ie "s/listen 8080/listen 80/g" /etc/nginx/sites-enabled/default
sed -ie "s/listen [::]:8080/listen [::]:80/g" /etc/nginx/sites-enabled/default
service nginx restart
