#!/usr/bin/env bash
# Script that automates fix for Ubuntu container Nginx installation
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
