#!/usr/bin/env bash
# Script that automates fix for Ubuntu container Nginx installation
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
