#!/usr/bin/env bash
# Script that automates fix like in task #0, in less than 5 lines
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
nginx -s stop
