#!/usr/bin/env bash
# Script that automates fix like in task #0, in less than 5 lines
ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
