#!/usr/bin/env bash
# Bash script with mutliple levels of functionality

pid="$(pgrep -f ./100-process_and_pid_file)"
echo "$pid" > /var/run/myscript.pid

while true; do
	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	echo "To infinity and beyond"
	sleep 2
done
