#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, displays "Best School" and then "Hi" on a new line
NUM=1
while ((NUM < 11)); do
	echo "Best School"
	if [ $NUM -eq 9 ]; then
		echo "Hi"
	fi
	((NUM++))
done
