#!/usr/bin/env bash
# Bash script that displays 'Best School' 10 times, printing 'Hi' after
# the 9th iteration using a 'while' loop and 'if' statement

i=0

while [ $i -ne 10 ]; do
    echo "Best School"
    if [ $i -eq 8 ]; then
        echo "Hi"
    fi
    ((i+=1))
done
