#!/usr/bin/env bash
# This script loops from 1 to 10 and displays "bad luck" for the 4th loop iteration, displays
# "good luck" for the 8th loop iteration, and displays "Best School" for the other iterations
NUM=1
while ((NUM < 11)); do
	if [ $NUM -eq 4 ]; then
		echo "bad luck"
	elif [ $NUM -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((NUM++))
done
