#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays "4" and then "bad luck from China" for the 4th loop iteration, displays "9" and
# then "bad luck from Japan" for the 9th loop iteration, and displays "17" and then "bad luck from Italy" for the 17th loop iteration
NUM=1
while ((NUM < 21)); do
	case $NUM in
		4)
			echo "$NUM"
			echo "bad luck from China"
			;;
		9)
			echo "$NUM"
			echo "bad luck from Japan"
			;;
		17)
			echo "$NUM"
			echo "bad luck from Italy"
			;;
		*)
			echo "$NUM"
			;;
	esac
	((NUM++))
done
