#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays "4" and then "bad luck from China" for the 4th loop iteration, displays "9" and
# then "bad luck from Japan" for the 9th loop iteration, and displays "17" and then "bad luck from Italy" for the 17th loop iteration
NUM=1
while ((NUM < 21)); do
	if [ $NUM -eq 4 ]; then
		echo "$NUM"
		echo "bad luck from China"
	elif [ $NUM -eq 9 ]; then
		echo "$NUM"
		echo "bad luck from Japan"
	elif [ $NUM -eq 17 ]; then
		echo "$NUM"
		echo "bad luck from Italy"
	else
		echo "$NUM"
	fi
	((NUM++))
done
