#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes, displaying hours from 0 to 12,
# and displaying minutes from 1 to 59 using a "while" loop
HOUR=0
while [ $HOUR -ne 13 ]; do
	echo "Hour: $HOUR"
	MINUTE=1
	while ((MINUTE != 60)); do
		echo "$MINUTE"
		((MINUTE++))
	done
	((HOUR++))
done
