#!/usr/bin/env bash
# Script that fixes a container that Nginx may run as 'nginx' user
sudo sed -ie "s/80/8080/g" /etc/nginx/sites-available/default
sudo sed -ie "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx restart
