#!/usr/bin/env bash
# Script that fixes a container that Nginx may run as 'nginx' user
sed -ie "s/80/8080/g" /etc/nginx/sites-available/default
sed -ie "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
